### ISSUE TITLE
Alguém me dá uma luz sobre o erro?

### ISSUE THREAD

**Issue by Marcelo15br** [claudiosmweb/woocommerce-checkout-cielo#12]
Ao finalizar a compra aparece "Oppsss!Ops! Ocorreu um erro inesperado."

12-17-2020 @ 16:14:43 - Transaction arguments for order 2491: Array
(
    [merchant_id] => 9ddd4084-...xxx
    [order_number] => 2491
    [antifraud_enabled] => TRUE
    [customer_name] => mdnsaf adfaf
    [customer_email] => marcelo.merito@xxx
    [customer_phone] => 15988123830
    [customer_identity] => 17726768886
    [shipping_address_name] => Rua C...xxx
    [shipping_address_number] => 389
    [shipping_address_complement] => 
    [shipping_address_district] => Jardim xxx
    [shipping_address_city] => xxx
    [shipping_address_state] => SP
    [shipping_zipcode] => xxx
    [shipping_type] => 2
    [shipping_1_name] => SEDEX
    [shipping_1_price] => 3309
    [cart_1_name] => FAROL 4" ELECTROLINE VINTAGE CROMADO E LENTE TRANSPARENTE
    [cart_1_unitprice] => 54999
    [cart_1_quantity] => 1
    [cart_1_type] => 1
    [cart_1_code] => 9020940331
    [cart_1_weight] => 845

**Comment by Marcelo15br** [comment]
erro no merchant id...

**Comment by vinibgoulart** [comment]
O que seria erro no merchantID? Estava colocando o merchantID errado?

To tendo o mesmo erro, porem meu merchantID parece estar correto, voce pegou o merchantID desse link? https://cieloecommerce.cielo.com.br/Backoffice/Merchant/Account/Details
